[project]
name = "fontend"
version = "0.1.0"
description = "UV project for the frontend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.1",
    "plotly>=6.2.0",
    "python-dotenv>=1.1.1",
    "streamlit>=1.48.0",
]
