#!/bin/bash
# \set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE ui WITH LOGIN PASSWORD '${UI_PASSWORD}';
    GRANT USAGE ON SCHEMA gold TO ui;
    ALTER DEFAULT PRIVILEGES IN SCHEMA gold GRANT SELECT ON TABLES TO ui;
    GRANT SELECT ON ALL TABLES IN SCHEMA gold TO ui;
EOSQL