services:
  timescaledb:
    build:
      dockerfile: Dockerfile
    container_name: datenkraken_db
    restart: unless-stopped
    ports:
      - "6000:5432"
    volumes:
      - datenkraken_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=datenkraken
      - UI_PASSWORD=${UI_PASSWORD}
      - DEV_PASSWORD=${DEV_PASSWORD}
    networks:
      - datenkraken-db-net

  pgadmin:
    image: dpage/pgadmin4:9.6.0
    container_name: datenkraken_pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "6001:80"
    depends_on:
      - timescaledb
    networks:
      - datenkraken-db-net

  
networks:
  datenkraken-db-net:
    external: true

volumes:
  datenkraken_db_data: