name: Run Frontend Tests

on:
  push:
    branches:
      - main
      - feature/testing-setup
  pull_request:

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest streamlit requests python-dotenv plotly pandas numpy

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          export WEATHER_API_KEY=dummy
          pytest frontend/tests
