name: Run Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv and dependencies
        run: |
          curl -Ls https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          ~/.local/bin/uv pip install -r requirements.txt
          ~/.local/bin/uv pip install pytest streamlit requests python-dotenv plotly pandas numpy

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          export WEATHER_API_KEY=dummy
          pytest frontend/tests
