name: Run Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pipx install uv

      - name: Sync dependencies from uv.lock
        run: uv sync --frozen

      - name: Run tests
        run: uv run pytest -q
